---
- name: Install ansible modules requirements
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - ansible-vector-role

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - ansible-lighthouse-role
