---
- name: Install ansible modules requirements
  hosts: clickhouse

  tasks:
    - name: Install python-firewall
      become: true
      ansible.builtin.yum:
        name: python-firewall, firewalld
        state: present

    - name: Start and enable firewalld
      become: true
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
      ignore_errors: "{{ ansible_check_mode }}"

- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:
    - name: Install Clickhouse
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "/tmp/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            mode: '0644'

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - /tmp/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm
          - /tmp/clickhouse-client-{{ clickhouse_version }}.x86_64.rpm
          - /tmp/clickhouse-server-{{ clickhouse_version }}.x86_64.rpm
        disable_gpg_check: true
      notify: Start clickhouse service
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Firewall open port
      become: true
      ansible.posix.firewalld:
        port: 9000/tcp
        state: enabled
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Pause 20 sec
      ansible.builtin.pause:
        seconds: 20

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
  tags: [clickhouse]

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Install vector package
      block:
        - name: Get vector package
          ansible.builtin.get_url:
            url: "https://yum.vector.dev/stable/vector-0/{{ vector_arch }}/vector-{{ vector_version }}.{{ vector_arch }}.rpm"
            dest: "/tmp/vector-{{ vector_version }}.{{ vector_arch }}.rpm"
            mode: '0644'

        - name: Install vector packages
          become: true
          ansible.builtin.yum:
            name:
              - /tmp/vector-{{ vector_version }}.{{ vector_arch }}.rpm
            disable_gpg_check: true
          notify: Start vector service
          ignore_errors: "{{ ansible_check_mode }}"

        - name: Deploy vector config
          become: true
          ansible.builtin.template:
            src: templates/vector.yaml.j2
            dest: /etc/vector/vector.yaml
            mode: '0644'

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers
  tags: [vector]

- name: Install Lighthouse
  hosts: lighthouse
  handlers:
    - name: Restart nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted

  tasks:
    - name: Add EPEL Repo
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Nginx and Git
      become: true
      ansible.builtin.yum:
        name: nginx, git
        state: present
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Start Nginx
      become: true
      ansible.builtin.systemd:
        service: nginx
        state: started
        enabled: true
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Create directory
      become: true
      ansible.builtin.file:
        path: "{{ lighthouse_dir }}"
        state: directory
        recurse: true
        mode: '0755'
        owner: nginx
        group: nginx

    - name: Clone lighthouse repo
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_git }}"
        version: master
        dest: "{{ lighthouse_dir }}"
        force: true
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Deploy nginx config
      become: true
      ansible.builtin.template:
        src: "templates/lighthouse.conf.j2"
        dest: "/etc/nginx/conf.d/lighthouse.conf"
        mode: '0644'

    - name: Add SELinux permissions
      become: true
      ansible.builtin.command: "chcon -vR system_u:object_r:httpd_sys_content_t:s0 {{ lighthouse_dir }}"
      changed_when: true
      notify: Restart nginx

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
  tags: [lighthouse]
