apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: netology
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: websecure
      port: 443
      targetPort: 443