apiVersion: v1
kind: Pod
metadata:
   name: multitool
   namespace: netology
spec:
   containers:
     - name: multitool
       image: praqma/network-multitool
       ports:
        - containerPort: 8080