apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
  namespace: netology
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
      nodePort: 30001    
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 1180
      nodePort: 30002