apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1
  namespace: netology
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi